package by.mordas.project.command;

public enum CommandType {
    SHOW_ALL_USERS,
    LOGIN,
    UPDATE_LOCALE,
    SHOW_ALL_FACULTY,
    FIND_SPECIALITY,
    USER_REGISTRATION,
    FIND_USER_SUBJECTS,
    CHANGE_USER_PASSWORD,
    CHOOSE_SPECIALITY,
    REGISTER_ON_SPECIALITY,
    ADD_FACULTY,
    DELETE_FACULTY,
    ADD_SPECIALITY,
    FIND_USER_BY_ID,
    DELETE_SPECIALITY
}
